apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  key: "ThisIsASecretKeyForJWTTokenGeneration123456789"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  username: "admin"
  password: "admin123"
